rfr: add unit tests
catenax-ng/product-traceability-foss-frontend pull request #3
Opened 2022-05-18 08:54 UTC by ds-ext-akononenko

2022-05-18 12:11 UTC, evia-fbedarf requested changes

2022-05-18 12:11 UTC, evia-fbedarf commented on src/app/modules/core/api/__mocks__/api.service.properties.ts
> +/**
This file should be src/app/mocks

And instead of naming it "api.service.properties", I would call it "api.model" so we stick with the naming conventions.

2022-05-18 12:11 UTC, evia-fbedarf commented on src/app/modules/page/dashboard/presentation/card/card.component.ts
> +  private static nextId = 0;
Could you explain to me why we need all this logic for the IDs?

Couldn't we use the label or something as ID?

2022-05-18 12:11 UTC, evia-fbedarf commented on src/app/modules/shared/components/button/button.component.spec.ts
> +    expect(screen.getByText('Test')).toBeInTheDocument();
Put this call in a variable so we don't have unnecessary calls:

const buttonElement = screen.getByText('Test') <= For Example.
expect(buttonElement).toBeInTheDocument();

2022-05-18 12:11 UTC, evia-fbedarf commented on src/app/modules/shared/components/button/button.component.html
> +  <button (click)="this.click.emit($event)" [disabled]="isDisabled" [ngClass]="getClasses()" mat-button>
Is the disabled attributed removed when "isDisabled" is false? If I can remember properly then the value has to be "null" so it disappears.

2022-05-18 12:30 UTC, ds-ext-akononenko commented on src/app/modules/core/api/__mocks__/api.service.properties.ts
> +/**
Shouldn't we stick to `jest` official approach for mocking modules?

2022-05-18 12:33 UTC, ds-ext-akononenko commented on src/app/modules/page/dashboard/presentation/card/card.component.ts
> +  private static nextId = 0;
`id` have to be unique per document.

We can have multiple `Card` components, so it means if we go with any static id it would clash.

In order to solve this, common approach is to generate unique id for each card component, monotonic id in general quite popular solution for this problem.

2022-05-18 12:41 UTC, ds-ext-akononenko commented on src/app/modules/shared/components/button/button.component.spec.ts
> +    expect(screen.getByText('Test')).toBeInTheDocument();
ok

2022-05-18 12:43 UTC, ds-ext-akononenko commented on src/app/modules/core/api/__mocks__/api.service.properties.ts
> +/**
my understanding that in `src/app/mocks` we have mocked API, this is mocked module, which is different thing

2022-05-19 07:59 UTC, evia-fbedarf commented on src/app/modules/core/api/__mocks__/api.service.properties.ts
> +/**
Ah, okay. Then I just misunderstood. Then its fine.

2022-05-24 07:23 UTC, ds-ext-akononenko commented on src/app/modules/page/dashboard/presentation/card/card.component.ts
> +  private static nextId = 0;
but I don't think this should be in layout state, as doing this leads to leaking card component internal value into external state, which breaks DX, and decrease component reusability.

I don't think that pure UI internal id should be moved to the external state, as there no other components/services or any other entity should be aware of this information.

2022-05-24 15:32 UTC, evia-fbedarf approved these changes

2022-05-25 07:06 UTC, merged