ftr: add hotel budapest helm chart
catenax-ng/product-traceability-foss-frontend pull request #4
Opened 2022-05-18 09:15 UTC by ds-ext-akononenko

2022-05-18 12:24 UTC, evia-fbedarf requested changes
I only understand half of what I just reviwed. I will ask JJ to take a look as well :).

2022-05-18 12:24 UTC, evia-fbedarf commented on chart/product-traceability-foss-frontend/.helmignore
> +.vscode/
No new line at the end of the file.

Please add a new line for all of the files added.

2022-05-18 12:24 UTC, evia-fbedarf commented on chart/product-traceability-foss-frontend/Chart.yaml
> +
Replace "Backend" with "Frontend"

2022-05-18 12:24 UTC, evia-fbedarf commented on chart/product-traceability-foss-frontend/templates/NOTES.txt
> +1. Get the application URL by running these commands:
Do we need this file?
If yes please use the .md file format.

2022-05-18 12:24 UTC, evia-fbedarf commented on chart/product-traceability-foss-frontend/templates/NOTES.txt
> +  export NODE_PORT=$(kubectl get --namespace {{ .Release.Namespace }} -o jsonpath="{.spec.ports[0].nodePort}" services {{ include "product-traceability-foss-backend.fullname" . }})
Replace "backend" with "frontend" in this file

2022-05-18 12:24 UTC, evia-fbedarf commented on chart/product-traceability-foss-frontend/templates/ingress.yaml
> +            backend:
Does this have to be "frontend"?

And is the configuration below the right one for a frontend?
Because "service", "serviceName" and "servicePort" seem redundant to me for a FE application.

2022-05-19 11:06 UTC, ds-ext-akononenko commented on chart/product-traceability-foss-frontend/templates/ingress.yaml
> +            backend:
yes, this is spec for the ingress

2022-05-19 11:17 UTC, ds-ext-akononenko commented on chart/product-traceability-foss-frontend/templates/NOTES.txt
> +1. Get the application URL by running these commands:
I've copy pasted it, seems everyone has it

2022-05-19 11:18 UTC, ds-ext-akononenko commented on chart/product-traceability-foss-frontend/Chart.yaml
> +
done

2022-05-19 13:07 UTC, ds-ext-akononenko commented on chart/product-traceability-foss-frontend/templates/NOTES.txt
> +  export NODE_PORT=$(kubectl get --namespace {{ .Release.Namespace }} -o jsonpath="{.spec.ports[0].nodePort}" services {{ include "product-traceability-foss-backend.fullname" . }})
done

2022-05-20 07:59 UTC, evia-fbedarf approved these changes

2022-05-20 08:01 UTC, evia-fbedarf approved these changes

2022-05-20 08:01 UTC, evia-fbedarf commented on chart/product-traceability-foss-frontend/Chart.yaml
> +description: A Helm chart for Traceability backend application
```suggestion
description: A Helm chart for Traceability frontend application
```

2022-05-20 08:01 UTC, evia-fbedarf commented on chart/product-traceability-foss-frontend/templates/deployment.yaml
> +            - name: http
Do we provide https?

2022-05-23 07:31 UTC, ds-ext-akononenko commented on chart/product-traceability-foss-frontend/templates/deployment.yaml
> +            - name: http
I believe https is implemented on the level above

2022-05-23 07:33 UTC, ds-ext-akononenko commented on chart/product-traceability-foss-frontend/templates/NOTES.txt
> +1. Get the application URL by running these commands:
this has to be named in this way, it used by helm chart

2022-05-23 08:42 UTC, merged