ftr: implement investigations inbox
catenax-ng/product-traceability-foss-frontend pull request #49
Opened 2022-07-27 05:16 UTC by ds-ext-akononenko

2022-07-27 06:48 UTC, evia-fbedarf requested changes

2022-07-27 06:48 UTC, evia-fbedarf commented on src/app/modules/core/auth/keycloak.helper.ts
>        realm = matches[1];
This part is useless, right?
If so, remove the if and the regex completly.

2022-07-27 06:48 UTC, evia-fbedarf commented on src/app/modules/core/layout/layout.routing.ts
> +    path: 'investigationsInbox',
I think it should just be "investigations" the inbox is redundant.

2022-07-27 06:48 UTC, evia-fbedarf commented on src/app/modules/page/investigationsInbox/presentation/investigationsInboxTab/investigationiInboxTab.component.ts
> +  readonly investigations$ = this.investigationsInboxFacade.investigations$;
public modifier is missing

2022-07-27 06:48 UTC, evia-fbedarf commented on src/app/modules/page/investigationsInbox/presentation/investigationsInbox.component.ts
> +  tabsByType = [InvestigationType.RECEIVED, InvestigationType.QUEUED, InvestigationType.REQUESTED];
public modifier is missing

2022-07-27 06:48 UTC, evia-fbedarf commented on src/app/modules/page/investigationsInbox/presentation/investigationsInbox.component.html
> +    <router-outlet></router-outlet>
Is there a reason why you implemented it like this?

It removes the tab switch animation from the tab component and flickers when switching tabs.
And there is a memory leak. When I switch tabs the data is loaded again, this should not happen.

And at first glance, it is too ambiguous what happens here.
This can be simplified and we should stick to it because of KISS.

2022-07-27 06:48 UTC, evia-fbedarf commented on src/app/modules/page/investigationsInbox/presentation/investigationsInbox.component.html
> +    <router-outlet></router-outlet>
Maybe take a look at "other parts" here the code works the same but with a lot less overhead.

2022-07-27 06:48 UTC, evia-fbedarf commented on src/app/modules/page/investigationsInbox/presentation/investigationsInbox.component.ts
> +  tabsByType = [InvestigationType.RECEIVED, InvestigationType.QUEUED, InvestigationType.REQUESTED];
I don't think this needs to be generic because we won't get more than 3 types.

2022-07-27 06:48 UTC, evia-fbedarf commented on src/app/modules/page/investigationsInbox/core/investigationsInbox.facade.ts
> +  private type$ = new Subject<InvestigationType>();
When changing the approach there is no need for all of this. Because the table remembers its state and the data is not reloaded on tab switch.

2022-07-27 06:48 UTC, evia-fbedarf commented on src/app/modules/page/investigationsInbox/core/investigationsInbox.facade.ts
> +      .subscribe({
A "first()" is missing to unsubscribe. Otherwise when switching the tabs, a lot of requests will be made.

2022-07-27 06:48 UTC, evia-fbedarf commented on src/app/modules/shared/components/table/table.component.ts
> +    const { active, direction } = event as unknown as Sort;
why are you doing this?

2022-07-27 09:40 UTC, ds-ext-akononenko commented on src/app/modules/page/investigationsInbox/core/investigationsInbox.facade.ts
> +      .subscribe({
switchMap internally does unsubscribe

2022-07-27 09:40 UTC, ds-ext-akononenko commented on src/app/modules/shared/components/table/table.component.ts
> +    const { active, direction } = event as unknown as Sort;
I will remove this one

2022-07-27 10:11 UTC, ds-ext-akononenko commented on src/app/modules/core/auth/keycloak.helper.ts
>        realm = matches[1];
it used in return statement

2022-07-27 10:11 UTC, ds-ext-akononenko commented on src/app/modules/page/investigationsInbox/presentation/investigationsInbox.component.ts
> +  tabsByType = [InvestigationType.RECEIVED, InvestigationType.QUEUED, InvestigationType.REQUESTED];
removed

2022-07-27 10:11 UTC, ds-ext-akononenko commented on src/app/modules/page/investigationsInbox/presentation/investigationsInbox.component.html
> +    <router-outlet></router-outlet>
redesigned

2022-07-27 10:12 UTC, ds-ext-akononenko commented on src/app/modules/page/investigationsInbox/core/investigationsInbox.facade.ts
> +  private type$ = new Subject<InvestigationType>();
redesigned

2022-07-27 19:20 UTC, evia-fbedarf requested changes

2022-07-27 19:20 UTC, evia-fbedarf commented on src/app/modules/page/investigations/core/investigations.facade.ts
> +  public setInvestigations() {
Why don't we separate "recieved" and "queued and request"?
And then we parameterise these functions with "page" and "pageSize". Then we can get rid of the pagination BehaviourSubjects and we can remove one layer of complexity.

Proposal:
```typescript
  public setReceivedInvestigation(page: number, pageSize: number): void {
    this.investigationsService.getInvestigetionsByType(InvestigationStatusGroup.RECEIVED, page, pageSize).subscribe({
      next: (data: Pagination<Investigation>) => (this.investigationsState.investigationsReceived = { data }),
      error: (error: Error) => (this.investigationsState.investigationsReceived = { error }),
    });
  }

  public setQueuedAndRequestedInvestigations(page: number, pageSize: number): void {
    this.investigationsService.getInvestigetionsByType(InvestigationStatusGroup.QUEUED_N_REQUESTED, page, pageSize).subscribe({
        next: (data: Pagination<Investigation>) => (this.investigationsState.investigationsQueuedNRequested = { data }),
        error: (error: Error) => (this.investigationsState.investigationsQueuedNRequested = { error }),
      });
  }
```

2022-07-27 19:20 UTC, evia-fbedarf commented on src/app/modules/page/investigations/core/investigations.service.ts
> +  public getInvestigetionsByType(
Typo in Investigetions => Investigations

2022-07-27 19:20 UTC, evia-fbedarf commented on src/app/modules/page/investigations/core/investigations.state.ts
> +  private readonly _investigationsQueuedNRequested$: State<View<Pagination<Investigation>>> = new State<
And please replace the "N" with "And" you save 2 chars by using N, and it is less readable

2022-07-27 19:20 UTC, evia-fbedarf commented on src/app/modules/page/investigations/presentation/investigationsTab/investigationsTab.component.html
> +  <p>{{ investigations.error }}</p>
class "regular-text" is missing.

2022-07-27 19:51 UTC, ds-ext-akononenko commented on src/app/modules/page/investigations/presentation/investigations.component.html
> +      <app-investigations-tab
yeah, I've seen other parts. I believe it's probably should be done inside of header component

2022-07-27 19:52 UTC, ds-ext-akononenko commented on src/app/modules/page/investigations/presentation/investigationStatus/investigationStatus.component.html
> +>
hmm, maybe. I will try to use it, however not very convinced

2022-07-27 19:53 UTC, ds-ext-akononenko commented on src/app/modules/page/investigations/core/investigations.state.ts
> +  private readonly _investigationsQueuedNRequested$: State<View<Pagination<Investigation>>> = new State<
Well, ok then, it can work out

2022-07-27 19:53 UTC, ds-ext-akononenko commented on src/app/modules/page/investigations/presentation/investigationsTab/investigationsTab.component.html
> +  <p>{{ investigations.error }}</p>
I will move this to new component, and will remove h1 usage here

2022-07-28 06:59 UTC, ds-ext-akononenko commented on src/app/modules/page/investigations/presentation/investigationStatus/investigationStatus.component.html
> +>
ok, I've tried, and it more problematic to make chip looks and works like label, so I would keep it as it is

2022-07-28 07:39 UTC, ds-ext-akononenko commented on src/app/modules/page/investigations/core/investigations.facade.ts
> +  public setInvestigations() {
we cannot get rid of observables/subjects. if user change pages quickly we can start new request which should discard the previous one. that's why it implemented in this way.

2022-07-28 07:39 UTC, ds-ext-akononenko commented on src/app/modules/page/investigations/presentation/investigationsTab/investigationsTab.component.html
> +  <p>{{ investigations.error }}</p>
moved

2022-07-28 07:39 UTC, ds-ext-akononenko commented on src/app/modules/page/investigations/core/investigations.state.ts
> +  private readonly _investigationsQueuedNRequested$: State<View<Pagination<Investigation>>> = new State<
done

2022-07-28 07:39 UTC, ds-ext-akononenko commented on src/app/modules/page/investigations/core/investigations.service.ts
> +  public getInvestigetionsByType(
done

2022-07-28 07:39 UTC, ds-ext-akononenko commented on src/app/mocks/services/investigations-mock/investigations.model.ts
> +export const buildInvestigations = (statuses: string[]): InvestigationResponse[] =>
done

2022-07-28 07:39 UTC, ds-ext-akononenko commented on src/app/modules/page/investigations/presentation/investigationsTab/investigationsTab.component.ts
> +  ngAfterViewInit(): void {
done

2022-07-28 07:40 UTC, ds-ext-akononenko commented on src/app/modules/page/investigations/presentation/investigations.component.html
> +      <app-investigations-tab
new component has been introduced

2022-07-28 07:40 UTC, ds-ext-akononenko commented on src/app/modules/page/investigations/core/investigations.state.ts
> +  private readonly _investigationsQueuedNRequested$: State<View<Pagination<Investigation>>> = new State<
changed

2022-07-29 06:02 UTC, evia-fbedarf commented on src/app/modules/shared/components/unscoped-styles.scss
> +@import './tabs/tab-as-panel.directive.scss';
Instead of doing this, you can do the following:
encapsulation: ViewEncapsulation.None,

Then the CSS is not scoped to the component and it will be placed in the main scope.

2022-07-29 06:03 UTC, evia-fbedarf approved these changes
LGMT

2022-07-29 06:04 UTC, evia-fbedarf commented on src/app/modules/shared/components/unscoped-styles.scss
> +@import './tabs/tab-as-panel.directive.scss';
`encapsulation: ViewEncapsulation.None,`
This belongs in the component int the @Component part.
Just like it is done in PartRelationComponent.

2022-07-29 06:08 UTC, merged