ftr: align translations
catenax-ng/product-traceability-foss-frontend pull request #57
Opened 2022-08-05 07:45 UTC by ds-ext-akononenko

2022-08-08 10:40 UTC, evia-fbedarf requested changes

2022-08-08 10:40 UTC, evia-fbedarf commented on src/app/modules/shared/components/pagination/paginator-intl.service.ts
> +    length = Math.max(length, 0);
What is the reason behind this? And shouldn't this be above the if?

2022-08-08 10:40 UTC, evia-fbedarf commented on src/app/modules/shared/components/pagination/paginator-intl.service.ts
> +    const endIndex = startIndex < length ? Math.min(startIndex + pageSize, length) : startIndex + pageSize;
This is kind of confusing. 
Do we really need that? I think this will look strange either way.

Example:
Page = 5,
PageSize = 5
Length = 20.

StatrIndex = 25.
endIndex = 20.

But I might just misunderstand the comment.

2022-08-08 10:40 UTC, evia-fbedarf commented on src/app/modules/shared/components/pagination/paginator-intl.service.ts
> +      startIndex: startIndex + 1,
Don't we also need the "+1"  for the end index?

It is kind of hard to visualize every edge-case just by looking at the code.

2022-08-08 10:40 UTC, evia-fbedarf commented on src/app/modules/shared/components/pagination/paginator-intl.service.ts
> +}
Please write some unit tests for this service.

2022-08-08 10:40 UTC, evia-fbedarf commented on src/app/modules/core/layout/layout.routing.ts
> +import { ABOUT_TOP_ROUTE } from '@page/about/about-route';
What do you think about this naming change:
..._TOP_ROUTE => ..._BASE_ROUTE

Because I think "top" is a bit meaningless or ambiguous.

2022-08-08 10:43 UTC, ds-ext-akononenko commented on src/app/modules/shared/components/pagination/paginator-intl.service.ts
> +    const endIndex = startIndex < length ? Math.min(startIndex + pageSize, length) : startIndex + pageSize;
I've copied it from angular material

2022-08-08 10:43 UTC, ds-ext-akononenko commented on src/app/modules/shared/components/pagination/paginator-intl.service.ts
> +    length = Math.max(length, 0);
again, I just copied it :)

2022-08-08 10:44 UTC, ds-ext-akononenko commented on src/app/modules/core/layout/sidebar/sidebar.component.ts
> +      const endUrl = r.urlAfterRedirects ?? r.url;
where `NavigationEnd ` event would lead in the end

2022-08-11 07:40 UTC, evia-fbedarf approved these changes
LGMT!

2022-08-11 10:59 UTC, merged