fix: address sonar issues
catenax-ng/product-traceability-foss-frontend pull request #62
Opened 2022-08-11 06:35 UTC by ds-ext-akononenko

2022-08-11 07:50 UTC, evia-fbedarf requested changes

2022-08-11 07:50 UTC, evia-fbedarf commented on src/app/modules/page/other-parts/presentation/other-parts.component.html
> +          params: { labelId: supplierTabLabelId }
could you use "customContext" instead of Params?

2022-08-11 07:50 UTC, evia-fbedarf commented on src/app/modules/shared/components/textarea/textarea.component.html
> +      (input)="onChange && onChange(getTextAreaFromEvent($event).value)"
Don't know if this works in HTML but what you could do is "onChange?.(...)"

2022-08-11 07:50 UTC, evia-fbedarf commented on src/app/modules/shared/directives/view-container.directive.ts
> +    for (const paramKey of Object.keys(this.params)) {
wouldn't something like `this.context = {...this.context, ...this.params }`  work?

2022-08-11 11:54 UTC, ds-ext-akononenko commented on src/app/modules/shared/directives/view-container.directive.ts
> +    for (const paramKey of Object.keys(this.params)) {
it's cannot be done like this (tests starting fail by some reason...)

however did some change here

2022-08-11 11:54 UTC, ds-ext-akononenko commented on src/app/modules/page/other-parts/presentation/other-parts.component.html
> +          params: { labelId: supplierTabLabelId }
changed

2022-08-12 06:03 UTC, ds-ext-akononenko commented on src/app/modules/shared/components/textarea/textarea.component.html
> +      (input)="onChange && onChange(getTextAreaFromEvent($event).value)"
changed

2022-08-12 06:46 UTC, evia-fbedarf approved these changes
LGTM

2022-08-12 06:49 UTC, merged