fix: update headers
catenax-ng/product-traceability-foss-frontend pull request #63
Opened 2022-08-11 07:09 UTC by ds-ext-akononenko

Update license header

2022-08-11 08:24 UTC, evia-fbedarf requested changes
Please Check all files again, I don't know if I got all the missing dots.

2022-08-11 08:24 UTC, evia-fbedarf commented on src/app/modules/shared/components/card-icon/card-icon.component.scss
> +card--icon {
. is missing

2022-08-11 08:24 UTC, evia-fbedarf commented on src/app/modules/shared/components/card-list/card-list.component.scss
> +card-list--container {
. is missing

2022-08-11 08:24 UTC, evia-fbedarf commented on src/app/modules/shared/components/sidenav/sidenav.component.scss
> +sidenav {
. is missing

2022-08-11 08:24 UTC, evia-fbedarf commented on src/app/modules/shared/modules/relations/presentation/part-relation.component.scss
> +part-relation--button-container {
. is missing

2022-08-11 12:07 UTC, ds-ext-akononenko commented
I've fixed scss files. There was wrong format

2022-08-12 06:44 UTC, evia-fbedarf approved these changes
LGMT

2022-08-12 06:49 UTC, merged