fix: textarea behaviour
catenax-ng/product-traceability-foss-frontend pull request #69
Opened 2022-08-18 04:50 UTC by ds-ext-akononenko

2022-08-18 13:11 UTC, evia-fbedarf requested changes

2022-08-18 13:11 UTC, evia-fbedarf commented on src/app/modules/shared/components/request-investigation/request-investigation.component.ts
> -        this.removedItemsHistory = [];
Why did you remove this here?
The deletion history should reset if the items change.

2022-08-18 13:11 UTC, evia-fbedarf commented on src/app/modules/shared/components/request-investigation/request-investigation.component.ts
> +import * as _ from 'lodash';
Please don't import lodash like this.
Importing it this way prevents treeshaking. Only import functions you directly need.

Is this import unused?

2022-08-18 13:11 UTC, evia-fbedarf commented on src/app/modules/shared/components/textarea/textarea.component.ts
> +      this.textareaRef.nativeElement.value = value ?? '';
First a question:
Why don't we pass the control to the textarea?

Second question:
Is it possible to use a Subject for this case?
Angular should trigger their change detection with an async pipe.
We should avoid this workaround by all means. This is not clean.

2022-08-19 03:23 UTC, ds-ext-akononenko commented on src/app/modules/shared/components/textarea/textarea.component.ts
> +      this.textareaRef.nativeElement.value = value ?? '';
there is some issue with angular and textarea `[value]`, manual change detection doesn't work, using `ngModel` doesn't work. Well, better to say it works for me first 2 times (which is even more odd, because if it wouldn't work just for the first time it's can be explainable, but not first 2 times...)

we cannot pass control to the textarea, as we reset value when we closing request form, which means that we set the value.

2022-08-19 03:24 UTC, ds-ext-akononenko commented on src/app/modules/shared/components/request-investigation/request-investigation.component.ts
> -        this.removedItemsHistory = [];
because it's happening in `set isOpen`, no need to do it twice

2022-08-19 03:25 UTC, ds-ext-akononenko commented on src/app/modules/shared/components/request-investigation/request-investigation.component.ts
> +import * as _ from 'lodash';
I have no idea how this got here...

2022-08-19 03:27 UTC, ds-ext-akononenko commented on src/app/modules/shared/components/request-investigation/request-investigation.component.ts
> -        this.removedItemsHistory = [];
addressed

2022-08-22 07:51 UTC, evia-fbedarf approved these changes

2022-08-23 13:08 UTC, merged