doc: add NOTICE and SECURITY files
catenax-ng/product-traceability-foss-frontend pull request #77
Opened 2022-09-06 04:47 UTC by ds-ext-akononenko

Currently I still don't fully understand how to create DEPENDENCIES file properly, without removing dependencies. Still working on it.

2022-09-06 04:48 UTC, ds-ext-akononenko commented on NOTICE.md
> +See yarn.lock file.
in template it should mention DEPENDENCIES file, however as it's not here for now, I've mentioned yarn.lock as a source of truth for all third parties.

2022-09-06 09:24 UTC, evia-fbedarf requested changes

2022-09-06 09:24 UTC, evia-fbedarf commented on NOTICE.md
> +# Notices
Where is the Apache-2.0 license file?

https://github.com/catenax-ng/foss-example/blob/main/general/LICENSE

2022-09-06 09:24 UTC, evia-fbedarf commented on NOTICE.md
> +See the AUTHORS file(s) distributed with this work for additional information regarding authorship.
This line can be removed because we don't have an Authors file.

2022-09-07 06:09 UTC, ds-ext-akononenko commented on NOTICE.md
> +# Notices
we already have it

2022-09-07 06:13 UTC, ds-ext-akononenko commented on NOTICE.md
> +See the AUTHORS file(s) distributed with this work for additional information regarding authorship.
changed

2022-09-07 06:46 UTC, evia-fbedarf approved these changes

2022-09-08 08:33 UTC, merged